[package]
name = "httpx-crypto"
version.workspace = true
edition.workspace = true

[dependencies]
httpx-core.workspace = true
chacha20poly1305.workspace = true
zeroize.workspace = true
bytes.workspace = true
